### ISSUE TITLE
Error setting up Mind platform

### ISSUE THREAD

**Issue by guyke01** [bramkragten/mind#7]
Since yesterday the Mind integration failed when rebooting Home Assistant. After several reboots the integration seems to be broken. The reinstall of the integration has not resolved the issue. The following error comes in the log:

HTTP Error mind API: 500 Server Error: Server Error for url: https://e-mind-api.eu.cloudhub.io/api/vehicles

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mind/sensor.py", line 38, in setup_platform
    for vehicle in hass.data[DATA_MIND].vehicles():
  File "/config/custom_components/mind/__init__.py", line 77, in vehicles
    for vehicle in self.mind.vehicles:
  File "/usr/local/lib/python3.9/site-packages/mind/__init__.py", line 403, in vehicles
    return [Vehicle(vehicle.get('vehicleId'), self, self._local_time)
TypeError: 'NoneType' object is not iterable

**Comment by guyke01** [comment]
This afternoon the integration start working again after a reboot. Probably something with the API Service.
